allowed_paths:
  - /home/$USER/Documents
  - /home/$USER/Projects
denied_paths:
  - /home/$USER/Documents/Secrets
allowed_commands:
  - echo
  - ls
  - cat
  - uname
  - date
denied_commands:
  - rm
  - sudo
  - powershell
require_approval: false
prompt_on_write: false
