name: Build ISO
on:
  workflow_dispatch:
jobs:
  iso:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - uses: actions/checkout@v3
      - run: echo "Build ISO for ${{ matrix.arch }}"
